### ISSUE TITLE
OpenSSL 1.0.2d: patch fails (4 out of 8)

### ISSUE THREAD

**Issue by HansVanEijsden** [cloudflare/sslconfig#15]
The patch worked fine on OpenSSL 1.0.2c, but not on 1.0.2d.

# patch --version
patch 2.6.1

# pwd
/usr/local/src/openssl-1.0.2d

# patch -p1 <openssl__chacha20_poly1305_cf.patch 
patching file Configure
Hunk #1 succeeded at 143 (offset 17 lines).
Hunk #2 succeeded at 706 (offset 17 lines).
Hunk #3 succeeded at 749 (offset 17 lines).
Hunk #4 succeeded at 1208 (offset 17 lines).
Hunk #5 succeeded at 1237 (offset 18 lines).
Hunk #6 succeeded at 1404 (offset 18 lines).
Hunk #7 succeeded at 1557 (offset 18 lines).
Hunk #8 succeeded at 1746 (offset 27 lines).
Hunk #9 succeeded at 1808 (offset 27 lines).
Hunk #10 succeeded at 2207 (offset 27 lines).
Hunk #11 succeeded at 2238 (offset 27 lines).
patching file Makefile.org
patching file apps/speed.c
patching file crypto/chacha20poly1305/Makefile
patching file crypto/chacha20poly1305/asm/chacha20_avx.pl
patching file crypto/chacha20poly1305/asm/chacha20_avx2.pl
patching file crypto/chacha20poly1305/asm/poly1305_avx.pl
patching file crypto/chacha20poly1305/asm/poly1305_avx2.pl
patching file crypto/chacha20poly1305/chacha20.c
patching file crypto/chacha20poly1305/chacha20poly1305.h
patching file crypto/chacha20poly1305/chapoly_test.c
patching file crypto/chacha20poly1305/poly1305.c
patching file crypto/cryptlib.c
patching file crypto/evp/Makefile
Hunk #3 succeeded at 265 (offset 2 lines).
patching file crypto/evp/e_chacha20poly1305.c
patching file crypto/evp/evp.h
Hunk #1 succeeded at 893 (offset 2 lines).
patching file ssl/s3_lib.c
patching file ssl/ssl.h
patching file ssl/ssl_ciph.c
Hunk #7 succeeded at 1818 (offset 6 lines).
patching file ssl/ssl_locl.h
patching file ssl/tls1.h
patching file test/Makefile
Hunk #1 FAILED at 68.
Hunk #2 FAILED at 80.
Hunk #3 FAILED at 93.
Hunk #4 FAILED at 103.
Hunk #5 succeeded at 140 (offset 1 line).
Hunk #6 succeeded at 354 with fuzz 2 (offset 5 lines).
Hunk #7 succeeded at 526 with fuzz 2 (offset 6 lines).
Hunk #8 succeeded at 857 (offset 24 lines).
4 out of 8 hunks FAILED -- saving rejects to file test/Makefile.rej

# cat test/Makefile.rej
http://pastebin.com/XjHZ464J

**Comment by memiux** [comment]
I've resolved the 4 conflicts in `test/Makefile`. Hopefully it should work.

https://gist.githubusercontent.com/memiux/ad79a92f0241ed40401b/raw/dab75171e9776ca2819399ea6fe71f3dd9248e19/openssl-1.0.2d__chacha20_poly1305_cf.patch

**Comment by as-com** [comment]
I made a PR: #16

**Comment by vkrasnov** [comment]
The patch applies cleanly now 1.0.2 stable, and only minor conflicts on 1.0.2d.
Also a version that applies to the master also available.
