### ISSUE TITLE
Explain Cipher Choice.

### ISSUE THREAD

**Issue by StormTide** [cloudflare/sslconfig#2]
The Cipher Spec listed resolves to the following on a typical OpenSSL 1.0.1g

ECDHE-RSA-AES128-GCM-SHA256
ECDHE-ECDSA-AES128-GCM-SHA256
ECDHE-RSA-AES128-SHA256
ECDHE-ECDSA-AES128-SHA256
ECDHE-RSA-AES128-SHA
ECDHE-ECDSA-AES128-SHA
AES128-GCM-SHA256
AES128-SHA256
AES128-SHA
ECDHE-RSA-AES256-GCM-SHA384
ECDHE-ECDSA-AES256-GCM-SHA384
ECDHE-RSA-AES256-SHA384
ECDHE-ECDSA-AES256-SHA384
ECDHE-RSA-AES256-SHA
ECDHE-ECDSA-AES256-SHA
AES256-GCM-SHA384
AES256-SHA256
AES256-SHA
ECDHE-RSA-DES-CBC3-SHA
ECDHE-ECDSA-DES-CBC3-SHA
DES-CBC3-SHA
ECDHE-RSA-RC4-SHA
ECDHE-ECDSA-RC4-SHA
RC4-SHA 

There might be good legacy support reasons to support some of these weaker ciphers, but it would be nice to know the browser overlap/reason for support.

**Comment by grittygrease** [comment]
Here is the latest:
https://blog.cloudflare.com/end-of-the-road-for-rc4/
