### ISSUE TITLE
apply openssl__chacha20_poly1305_cf.patch filed

### ISSUE THREAD

**Issue by Kuras** [cloudflare/sslconfig#20]
OS: {Linux vagrant-opensuse-132-64 3.16.7-21-default #1 SMP Tue Apr 14 07:11:37 UTC 2015 (93c1539) x86_64 x86_64 x86_64 GNU/Linux}

OpenSSL: {openssl-1.0.2, openssl-1.0.2a, openssl-1.0.2b, openssl-1.0.2c, openssl-1.0.2d}

Patch: {2.7.5}

pwd: {/home/vagrant/Sources/openssl-1.0.2(a|b|c|d)}

$ patch -p1 --dry-run < openssl__chacha20_poly1305_cf.patch

checking file Configure
Hunk #1 succeeded at 126 (offset -17 lines).
Hunk #2 succeeded at 689 (offset -17 lines).
Hunk #3 succeeded at 732 (offset -17 lines).
Hunk #4 succeeded at 1191 (offset -17 lines).
Hunk #5 succeeded at 1219 (offset -18 lines).
Hunk #6 succeeded at 1386 (offset -18 lines).
Hunk #7 succeeded at 1539 (offset -18 lines).
Hunk #8 succeeded at 1717 (offset -27 lines).
Hunk #9 succeeded at 1781 (offset -27 lines).
Hunk #10 succeeded at 2180 (offset -27 lines).
Hunk #11 succeeded at 2211 (offset -27 lines).
checking file Makefile.org
checking file apps/speed.c
checking file crypto/chacha20poly1305/Makefile
checking file crypto/chacha20poly1305/asm/chacha20_avx.pl
checking file crypto/chacha20poly1305/asm/chacha20_avx2.pl
checking file crypto/chacha20poly1305/asm/poly1305_avx.pl
checking file crypto/chacha20poly1305/asm/poly1305_avx2.pl
checking file crypto/chacha20poly1305/chacha20.c
checking file crypto/chacha20poly1305/chacha20poly1305.h
checking file crypto/chacha20poly1305/chapolytest.c
checking file crypto/chacha20poly1305/poly1305.c
checking file crypto/cryptlib.c
checking file crypto/crypto.h
checking file crypto/evp/Makefile
Hunk #3 succeeded at 263 (offset -2 lines).
checking file crypto/evp/e_chacha20poly1305.c
checking file crypto/evp/evp.h
Hunk #1 succeeded at 891 (offset -2 lines).
checking file crypto/objects/obj_dat.h
checking file crypto/objects/obj_mac.h
checking file ssl/s3_lib.c
checking file ssl/ssl.h
checking file ssl/ssl_algs.c
checking file ssl/ssl_ciph.c
Hunk #6 succeeded at 1824 (offset -7 lines).
checking file ssl/ssl_locl.h
checking file ssl/tls1.h
checking file test/Makefile
Hunk #1 FAILED at 70.
Hunk #2 FAILED at 83.
Hunk #3 FAILED at 97.
Hunk #4 FAILED at 108.
Hunk #5 succeeded at 138 (offset -6 lines).
Hunk #6 succeeded at 344 with fuzz 2 (offset -17 lines).
Hunk #7 succeeded at 515 with fuzz 2 (offset -27 lines).
Hunk #8 succeeded at 566 (offset -46 lines).
4 out of 8 hunks FAILED

**Comment by v998** [comment]
First, please use the backticks 
You are making references to some of the other issues. (which is not related to this issue)
see https://help.github.com/articles/markdown-basics/

Second, the patch fail only occurs on `test/Makefile`, which is only used in `make test`
You can still build and use the patched OpenSSL without any issues.

**Comment by vkrasnov** [comment]
Thank you @v998, that is indeed the case.

**Comment by Kuras** [comment]
**Thank you  ;)**

**Comment by frostieDE** [comment]
And the same again for 1.0.2e :P

```
root@ubuntu-vm:/opt/openssl-1.0.2e# patch -p1 --dry-run < ../openssl__chacha20_poly1305_cf_latest_git.patch
checking file Configure
Hunk #1 FAILED at 346.
Hunk #2 FAILED at 490.
Hunk #3 succeeded at 757 with fuzz 2 (offset -34 lines).
Hunk #4 FAILED at 1269.
Hunk #5 FAILED at 1380.
Hunk #6 succeeded at 1611 (offset 12 lines).
Hunk #7 succeeded at 1746 (offset 12 lines).
Hunk #8 succeeded at 1807 (offset 15 lines).
Hunk #9 FAILED at 2221.
Hunk #10 FAILED at 2259.
6 out of 10 hunks FAILED
checking file Makefile.org
Hunk #1 succeeded at 93 (offset -2 lines).
Hunk #2 FAILED at 144.
Hunk #3 succeeded at 236 with fuzz 1 (offset 1 line).
1 out of 3 hunks FAILED
checking file apps/speed.c
Hunk #1 FAILED at 190.
Hunk #2 FAILED at 207.
Hunk #3 succeeded at 256 (offset 32 lines).
Hunk #4 FAILED at 405.
Hunk #5 FAILED at 474.
Hunk #6 succeeded at 1370 with fuzz 1 (offset 301 lines).
Hunk #7 FAILED at 1513.
5 out of 7 hunks FAILED
checking file crypto/chacha20poly1305/Makefile
checking file crypto/chacha20poly1305/asm/chacha20_avx.pl
checking file crypto/chacha20poly1305/asm/chacha20_avx2.pl
checking file crypto/chacha20poly1305/asm/poly1305_avx.pl
checking file crypto/chacha20poly1305/asm/poly1305_avx2.pl
checking file crypto/chacha20poly1305/chacha20.c
checking file crypto/chacha20poly1305/poly1305.c
checking file crypto/evp/Makefile
Hunk #1 succeeded at 29 with fuzz 2 (offset 3 lines).
Hunk #2 succeeded at 43 with fuzz 2 (offset 3 lines).
Hunk #3 FAILED at 252.
1 out of 3 hunks FAILED
checking file crypto/evp/e_chacha20poly1305.c
checking file crypto/objects/obj_dat.h
Hunk #1 FAILED at 62.
Hunk #2 FAILED at 2658.
Hunk #3 succeeded at 2954 (offset -165 lines).
Hunk #4 succeeded at 3729 (offset -227 lines).
2 out of 4 hunks FAILED
checking file include/openssl/chacha20poly1305.h
File include/openssl/evp.h is not a regular file -- refusing to patch
1 out of 1 hunk ignored
File include/openssl/obj_mac.h is not a regular file -- refusing to patch
1 out of 1 hunk ignored
File include/openssl/ssl.h is not a regular file -- refusing to patch
1 out of 1 hunk ignored
File include/openssl/tls1.h is not a regular file -- refusing to patch
2 out of 2 hunks ignored
checking file ssl/s3_lib.c
Hunk #1 succeeded at 2891 with fuzz 2 (offset -879 lines).
Hunk #2 succeeded at 4095 with fuzz 2 (offset -749 lines).
Hunk #3 succeeded at 4129 (offset -748 lines).
Hunk #4 FAILED at 4898.
1 out of 4 hunks FAILED
checking file ssl/ssl_algs.c
Hunk #1 succeeded at 105 (offset 3 lines).
checking file ssl/ssl_ciph.c
Hunk #1 FAILED at 150.
Hunk #2 FAILED at 196.
Hunk #3 succeeded at 316 (offset -62 lines).
Hunk #4 succeeded at 1825 (offset 79 lines).
2 out of 4 hunks FAILED
checking file ssl/ssl_locl.h
Hunk #1 FAILED at 363.
1 out of 1 hunk FAILED
checking file test/Makefile
Hunk #1 FAILED at 78.
Hunk #2 FAILED at 97.
Hunk #3 FAILED at 113.
Hunk #4 FAILED at 126.
Hunk #5 succeeded at 396 with fuzz 2 (offset 163 lines).
Hunk #6 succeeded at 884 (offset 164 lines).
4 out of 6 hunks FAILED
checking file test/chapolytest.c
checking file test/recipes/05-test_chacha20poly1305.t
```

(Ubuntu 14.04.3 LTS x64)
