### ISSUE TITLE
Build Fails: suffix or operands invalid for `vpunpcklqdq'

### ISSUE THREAD

**Issue by move-zig** [cloudflare/sslconfig#32]
Running CentOS 6.7, the latest 1.0.2g patch applies to the 1.0.2g openssl source without error, but make fails:

```
poly1305_avx2.s: Assembler messages:
poly1305_avx2.s:335: Error: suffix or operands invalid for `vpunpcklqdq'
poly1305_avx2.s:336: Error: suffix or operands invalid for `vpunpckhqdq'
poly1305_avx2.s:338: Error: no such instruction: `vpermq $0xD8,%ymm7,%ymm7'
poly1305_avx2.s:339: Error: no such instruction: `vpermq $0xD8,%ymm8,%ymm8'
poly1305_avx2.s:341: Error: suffix or operands invalid for `vpsrlq'
poly1305_avx2.s:342: Error: suffix or operands invalid for `vpand'
poly1305_avx2.s:343: Error: suffix or operands invalid for `vpaddq'
```

Is this due to an instruction set my CPU is missing? I'm running a cloud server on Rackspace.

[cpuinfo.txt](https://github.com/cloudflare/sslconfig/files/169181/cpuinfo.txt)

[patch-results.txt](https://github.com/cloudflare/sslconfig/files/169172/patch-results.txt)
[config-results.txt](https://github.com/cloudflare/sslconfig/files/169173/config-results.txt)
[make-depend-results.txt](https://github.com/cloudflare/sslconfig/files/169174/make-depend-results.txt)
[make-results.txt](https://github.com/cloudflare/sslconfig/files/169175/make-results.txt)

**Comment by move-zig** [comment]
I [installed devtools-2](https://gist.github.com/stephenturner/e3bc5cfacc2dc67eca8b) for Centos 6.7 to get gcc 4.8.

The build got farther along. Now I'm at this point:

```
../libcrypto.a(chacha20.o): In function `CRYPTO_chacha_20':
chacha20.c:(.text+0x40): undefined reference to `chacha_20_core_avx2'
collect2: error: ld returned 1 exit status
make[2]: *** [link_app.] Error 1
make[2]: Leaving directory `/usr/local/src/openssl-1.0.2g-patched/apps'
make[1]: *** [openssl] Error 2
make[1]: Leaving directory `/usr/local/src/openssl-1.0.2g-patched/apps'
make: *** [build_apps] Error 1
```

...which I think is described in a previous issue.

**Comment by anirudhvr** [comment]
I've seen this before - gcc 4.8 assembler doesn't seem to understand these. Try gcc 4.9+

**Comment by v998** [comment]
FYI, [devtoolset-3](https://www.softwarecollections.org/en/scls/rhscl/devtoolset-3/) has gcc 4.9.1

**Comment by liujen** [comment]
Try upgrade the binutils version to 2.2.22 or above

**Comment by vkrasnov** [comment]
Should not compile avx2 when not supported anymore.
