### ISSUE TITLE
when will the version  compatible with OpenSSL 1.0.2h be updated?

### ISSUE THREAD

**Issue by zwl1619** [cloudflare/sslconfig#37]
when will the version  compatible with OpenSSL 1.0.2h be updated?

**Comment by frostieDE** [comment]
The [1.0.2g patch](https://github.com/cloudflare/sslconfig/blob/master/patches/openssl__chacha20_poly1305_draft_and_rfc_ossl102g.patch) works fine with 1.0.2h (at least for amd64, as I successfully compiled it on arch amd64).

**Comment by Angristan** [comment]
I also use it on OpenSSL 1.0.2h without any issue.
