### ISSUE TITLE
OpenSSL 1.0.2h failed to link on Visual Studio 2013

### ISSUE THREAD

**Issue by trippleflux** [cloudflare/sslconfig#43]
I am using the latest "openssl__chacha20_poly1305_draft_and_rfc_ossl102g.patch" patch on OpenSSL 1.0.2h compiling using Visual Studio 2013 x64 command prompt, vanilla 1.0.2h managed to compile but successfully patched chacha draft will resulting link error at the end : 

C:\Users\Users1\Documents\Works\Compiling\openssl-1.0.2h>nmake -f ms\nt.mak

Microsoft (R) Program Maintenance Utility Version 12.00.21005.1
Copyright (C) Microsoft Corporation.  All rights reserved.

Building OpenSSL
        link /nologo /subsystem:console /opt:ref /debug /out:out32\ssltest.exe @C:\Users\Users1\AppData\Local\Temp\nmF932.tmp
libeay32.lib(e_chacha20poly1305.obj) : error LNK2019: unresolved external symbol CRYPTO_chacha_20 referenced in function EVP_chacha20_poly1305_cipher
libeay32.lib(e_chacha20poly1305.obj) : error LNK2019: unresolved external symbol poly1305_init_x64 referenced in function EVP_chacha20_poly1305_cpuid
libeay32.lib(e_chacha20poly1305.obj) : error LNK2019: unresolved external symbol poly1305_update_x64 referenced in function EVP_chacha20_poly1305_cpuid
libeay32.lib(e_chacha20poly1305.obj) : error LNK2019: unresolved external symbol poly1305_finish_x64 referenced in function EVP_chacha20_poly1305_cpuid
libeay32.lib(e_chacha20poly1305.obj) : error LNK2019: unresolved external symbol poly1305_update_avx2 referenced in function EVP_chacha20_poly1305_cpuid
libeay32.lib(e_chacha20poly1305.obj) : error LNK2019: unresolved external symbol poly1305_finish_avx2 referenced in function EVP_chacha20_poly1305_cpuid
out32\ssltest.exe : fatal error LNK1120: 6 unresolved externals
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\amd64\link.EXE"' : return code '0x460'
Stop.

**Comment by HansVanEijsden** [comment]
(Slightly offtopic, but while you're on it: important OpenSSL 1.0.2i security update just came out.)

**Comment by trippleflux** [comment]
Yup, using 1.0.2i i am also experiencing the same patch failed.

**Comment by vkrasnov** [comment]
We don't really support windows. I might fix in the next update though.
