### ISSUE TITLE
Rebase 'nginx__dynamic_tls_records.patch' to nginx 1.11.5

### ISSUE THREAD

**Issue by leonklingele** [cloudflare/sslconfig#45]
Looks like `nginx__dynamic_tls_records.patch` no longer applies to nginx 1.11.5.
Here's a refreshed patch: https://gist.github.com/leonklingele/b5ea3eeeed2a799bab31856c49f80255

**Comment by HansVanEijsden** [comment]
Working great again, thank you very much.

**Comment by rugk** [comment]
Why not create a PR?

**Comment by leonklingele** [comment]
I guess Cloudflare prefers to use nginx stable. This patch however only works for the latest nginx mainline version (1.11.5)

**Comment by vkrasnov** [comment]
Hi @leonklingele, thanks for the effort. If you create a PR with this patch as a new file, I will be happy to merge it. Something like "nginx_1.11.5_dynamic_tls_records.patch".
