### ISSUE TITLE
problems with nginx-spdy-1.11.5+.patch when it is applied to nginx version 1.11.11

### ISSUE THREAD

**Issue by amirymk** [cloudflare/sslconfig#62]
There is a problem with theis patch when it is applied to nginx version 1.11.11
[root@server nginx-1.11.11]# patch -p1 < ./nginx-spdy-1.11.5+.patch patching file auto/modules
Hunk #1 FAILED at 139.
Hunk #2 FAILED at 171.
Hunk #3 FAILED at 232.
Hunk #4 FAILED at 440.
4 out of 4 hunks FAILED -- saving rejects to file auto/modules.rej
patching file auto/options

**Comment by Injust** [comment]
Added new versions in #63

**Comment by cujanovic** [comment]
Can you please this one?

https://raw.githubusercontent.com/cujanovic/nginx-http2-spdy-patch/master/nginx-spdy-1.11.11%2B.patch

**Comment by amirymk** [comment]
Excellent
The problem has been resolved
thank you very much

**Comment by infinityhacks** [comment]
@cujanovic  I tried the patch with Nginx 1.12.0 .but it seems like the spdy is not working.
