### ISSUE TITLE
error with nginx__dynamic_tls_records.patch when it is applied to nginx version 1.13.0

### ISSUE THREAD

**Issue by amirymk** [cloudflare/sslconfig#64]
There is a problem with theis patch when it is applied to nginx version 1.13.0
root@server:~/nginx-1.13.0# patch -p1 < ./nginx__dynamic_tls_records.patch
patching file src/event/ngx_event_openssl.c
Hunk #1 succeeded at 1173 (offset 136 lines).
Hunk #2 succeeded at 1712 (offset 136 lines).
Hunk #3 succeeded at 1848 (offset 136 lines).
patching file src/event/ngx_event_openssl.h
Hunk #1 FAILED at 38.
Hunk #2 FAILED at 63.
Hunk #3 succeeded at 94 (offset 22 lines).
2 out of 3 hunks FAILED -- saving rejects to file src/event/ngx_event_openssl.h.rej
patching file src/http/modules/ngx_http_ssl_module.c
Hunk #1 succeeded at 234 (offset 1 line).
Hunk #2 succeeded at 590 (offset 23 lines).
Hunk #3 succeeded at 660 (offset 24 lines).
Hunk #4 succeeded at 854 (offset 27 lines).
patching file src/http/modules/ngx_http_ssl_module.h
Hunk #1 succeeded at 57 (offset 1 line).

**Comment by leonklingele** [comment]
Try the [nginx__1.11.5_dynamic_tls_records.patch](https://github.com/cloudflare/sslconfig/blob/master/patches/nginx__1.11.5_dynamic_tls_records.patch):

```txt
$ patch -p1 < nginx__1.11.5_dynamic_tls_records.patch
patching file src/event/ngx_event_openssl.c
Hunk #1 succeeded at 1173 (offset 42 lines).
Hunk #2 succeeded at 1712 (offset 42 lines).
Hunk #3 succeeded at 1848 (offset 42 lines).
patching file src/event/ngx_event_openssl.h
Hunk #1 succeeded at 59 with fuzz 1 (offset 5 lines).
Hunk #2 succeeded at 94 (offset 5 lines).
Hunk #3 succeeded at 107 (offset 5 lines).
patching file src/http/modules/ngx_http_ssl_module.c
Hunk #1 succeeded at 234 (offset 1 line).
Hunk #2 succeeded at 590 (offset 22 lines).
Hunk #3 succeeded at 660 (offset 22 lines).
Hunk #4 succeeded at 854 (offset 22 lines).
patching file src/http/modules/ngx_http_ssl_module.h
```

**Comment by Angristan** [comment]
Nginx 1.13 works with nginx__1.11.5_dynamic_tls_records.patch
