### ISSUE TITLE
What does exact mean about time in 1369 = 1500 - 40 (IP) - 20 (TCP) - 10 (Time) - 61 (Max TLS overhead)

### ISSUE THREAD

**Issue by cocomoma** [cloudflare/sslconfig#68]
hello, when i read the nginx__dynamic_tls_records.patch, i see the formule 1369 = 1500 - 40 (IP) - 20 (TCP) - 10 (Time) - 61 (Max TLS overhead), but i don't know What  exact mean about time

**Comment by vkrasnov** [comment]
It is a TCP option https://en.wikipedia.org/wiki/Transmission_Control_Protocol#TCP_timestamps
