### ISSUE TITLE
dynamic_tls_records does not Reduce latency

### ISSUE THREAD

**Issue by cocomoma** [cloudflare/sslconfig#69]
server: CentOS release 6.4 (Final) kernel 2.6.32-358.el6.x86_64
nginx:1.10.2
openssl:1.0.1
patch:nginx__dynamic_tls_records.patch
hello,  when i test patch with different parameter, the test result show ttfb Reduce latency,but the whole latency of request does not reduce. The latency from my client to nginx server is about 30ms. Does the patch is better when used in bad network？

**Comment by vkrasnov** [comment]
It would only reduce ttfb. If you have a large request you won't see much difference. And yes, it is supposed to be better on bad networks.
