### ISSUE TITLE
ssl_ciphers syntax

### ISSUE THREAD

**Issue by blagoeres** [cloudflare/sslconfig#76]
Hi. I noticed new syntax for `ssl_ciphers` directive in conf file. I tried it but I get syntax error. How is this valid syntax ?

**Comment by Injust** [comment]
This is the syntax for BoringSSL's bracketed equal-preference groups, which is not supported by OpenSSL.

**Comment by HansVanEijsden** [comment]
Or... use this patch on OpenSSL 1.1.0f: https://gitlab.com/buik/openssl/blob/openssl-patch/openssl-1.1/OpenSSL1.1f-equal-preference-cipher-groups.patch

**Comment by blagoeres** [comment]
I was just curious about the syntax. I compiled nginx with openssl 1.1.0f and it didn't work. So either using boringssl or pathing openssl is an option. A lot of work. I am giving up. Thanks for help.
