### ISSUE TITLE
Support ChaCha20 Draft Ciphers in OpenSSL 1.1

### ISSUE THREAD

**Issue by kerzyte** [cloudflare/sslconfig#78]
The OpenSSL 1.0.2j patch for adding Chacha20 support does not work on OpenSSL 1.1. OpenSSL 1.1 added support for the final version of ChaCha20, but I would like to add the draft version back in for older clients.
Any chance that patch could be ported over?

**Comment by vkrasnov** [comment]
No, that would be too much work I'm afraid.

**Comment by kerzyte** [comment]
Understandable. What is Cloudflare using to be able to have both versions AND x25519?

**Comment by vkrasnov** [comment]
We are using boringssl, with a patch for old chacha

**Comment by RoldanLT** [comment]
Any chance the patch for BoringSSL will be public also?

**Comment by xetorixik** [comment]
@RoldanLT Vanilla BoringSSL and the old chacha patch for BoringSSL is quite useless for websites as BoringSSL doesn't support OCSP, Nginx multi cert? etc. 

It is only interesting if multiple BoringSSL patches (i.e. OCSP) are released. 
To re-add features those features that Google  has deleted.

@vkrasnov But. It seems unlikely to me that this will happen.

**Comment by Injust** [comment]
@xetorixik OCSP protocol was removed, but stapling and parsing are still in BoringSSL.

**Comment by HamJin** [comment]
Now where can I get the patch for boringssl?
