### ISSUE TITLE
Why EECDH+3DES?

### ISSUE THREAD

**Issue by vincentbernat** [cloudflare/sslconfig#8]
`EECDH+3DES` expands to:

```
ECDHE-RSA-DES-CBC3-SHA  SSLv3 Kx=ECDH     Au=RSA  Enc=3DES(168) Mac=SHA1
ECDHE-ECDSA-DES-CBC3-SHA SSLv3 Kx=ECDH     Au=ECDSA Enc=3DES(168) Mac=SHA1
```

Is there browser not supporting AES but supporting ECDH key exchange?

It was added in https://github.com/cloudflare/sslconfig/commit/9d5369e6f31615df18f7d964137fca3b7573a432.

**Comment by vkrasnov** [comment]
Indeed we are seeing some ECDHE with 3DES.
