### ISSUE TITLE
Port CHACHA20-POLY1305-OLD into openssl 1.1?

### ISSUE THREAD

**Issue by CarterLi** [cloudflare/sslconfig#80]
Only Android 7+ support new chacha20. As Android 5 & 6 are still commonly used, I think it's a good idea to support old chacha20 too.

**Comment by Injust** [comment]
Duplicate of #78

**Comment by CarterLi** [comment]
OK

**Comment by HamJin** [comment]
Now where can I get the patch for boringssl?
