### ISSUE TITLE
openssl__1.1.0_chacha20_poly1305.patch for openssl 1.1.1-dev

### ISSUE THREAD

**Issue by historype** [cloudflare/sslconfig#82]
I recently update my openssl for tls 1.3.So I cannot use openssl__1.1.0_chacha20_poly1305.patch.
But I want to use it.Is there a patch for openssl 1.1.1?

**Comment by CarterLi** [comment]
I resolved those conflicts: https://gist.github.com/CarterLi/dd80535db40b61baa60ba536fdb729f9

**Comment by historype** [comment]
Thanks @CarterLi .
