### ISSUE TITLE
RC4 patch for OpenSSL 1.0.2?

### ISSUE THREAD

**Issue by v998** [cloudflare/sslconfig#9]
The current ` patches/openssl__disable_rc4.patch ` only allows patching with 1.0.1.

Since you have released a Chacha20-Poly1305 patch for 1.0.2, 
should you also include a RC4 patch for 1.0.2?

**Comment by v998** [comment]
RC4 should not be used for HTTPS connection anymore.
So disabling it completely at the protocol level would be better.

**Comment by PiotrSikora** [comment]
RC4 has been disabled since d6529d3c.
